# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60109355c24e9fdbddf0ff7445451e87ee2a0b31ec11741b9b75621b2d5438a52c2c04903c0a731fbd30d413c77872f8d668a1e8a7de30441da6be7e30b17b44

test:
  secret_key_base: a08741a89773b561f474af96a1c71308a65efc17b84accd2830722a9fd966046526af042cf7f3070d7f31dcf938d7d1174e4d260ab47f0baf9ae3d5847047057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a08741a89773b561f474af96a1c71308a65efc17b84accd2830722a9fd966046526af042cf7f3070d7f31dcf938d7d1174e4d260ab47f0baf9ae3d5847047057
